### PR TITLE
Enhancements for TDTPy

### PR DESCRIPTION
**Pull request by buranconsult**
This includes:
* Support for using TDTPy in threads (required some modification to get the ActiveX library to initialize properly). 
* Fixes to bring up to latest Numpy/Python compatibility
* Support for incremential/continuous writes to output buffers.

### CODE REVIEW

**Comment by buranconsult** [comment]
Note that these changes were contributed by Decibel Therapeutics, which has asked for acknowledgement of their support. I have added a note to the readme file listing authors/contributors. Please add anyone else I may have left off.

**Comment by larsoner** [comment]
Code changes LGTM. I do not currently have (easy) access to a TDT to test this. Have you tested these at all @buranconsult ? If not I guess we can trust Decibel to have tested it.

Was the `CoInitialize` what was required to get threading to work?

**Comment by buranconsult** [comment]
I made the changes on behalf of Decibel and can confirm it works fine with
some software I wrote for them. The changes were required to get TDT
hardware (using TDTPy as a wrapper) working with psiexperiment (
https://github.com/bburan/psiexperiment). Look for a future release of
psiexperiment which will then support both National Instruments and TDT
hardware (allowing us to write an experiment once and run it on either
system -- some limitations apply of course).

`CoInitialize` was required to get threading to work properly.

**Comment by larsoner** [comment]
Cool, thanks for filling in the gaps @bburan

**Pull request merged**
