### PR TITLE
Add long-overdue unit tests

### PR DESCRIPTION
**Pull request by bburan**

### CODE REVIEW

**Comment by larsoner** [comment]
Do you want to add `codecov` here, too? It's pretty easy to adapt these files/lines I think:

https://github.com/mne-tools/mne-python/blob/main/.coveragerc
https://github.com/mne-tools/mne-python/blob/main/codecov.yml
https://github.com/mne-tools/mne-python/blob/main/azure-pipelines.yml#L129-L133

**Comment by bburan** [comment]
@larsoner Are you talking about automating the pytest? The tests will only work on a platform that's connected to a TDT system. Right now only systems with the RZ6 will work, but the tests don't *require* that other than the fact that the only test circuit I created is compiled against the RZ6. Would there be any benefit to adding `codecov` given that none of the current tests would work as part of the automated process?

**Comment by larsoner** [comment]
Oh no, I didn't look that closely and assumed that the circuit maybe somehow had a debug mode where it faked the right responses for tests. Never mind!

**Comment by larsoner** [comment]
Thanks @bburan

**Comment by bburan** [comment]
@larsoner It would be a nice feature to have a simulated circuit for debugging. Perhaps someday if I need to do much more work on TDPy I can add that. Thanks for merging this!

**Pull request merged**
